spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/experiment?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 147258

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"